
/**
 * Do not edit this file directly.
 *
 * The file is automatically generated as part of the ivh-base-components
 * library. Changes made here will be overwritten.
 */

import React from 'react'

export const AuBadge = (props) => {
  const {
    className,
    info,
    primary,
    success,
    warning,
    danger,
    ...passThroughProps
  } = props

  const _className = [
    className,
    'au-badge',
    info && 'au-badge-info',
    primary && 'au-badge-primary',
    success && 'au-badge-success',
    warning && 'au-badge-warning',
    danger && 'au-badge-danger'
  ]
  .filter(Boolean).join(' ')

  const Cmp = props.cmp || 'span'

  return <Cmp
    className={_className}
    {...passThroughProps} />
}

export const AuWithBadge = (props) => {
  const {
    className,
    ...passThroughProps
  } = props

  const _className = [
    className,
    'au-with-badge',
    0
  ]
  .filter(Boolean).join(' ')

  const Cmp = props.cmp || 'span'

  return <Cmp
    className={_className}
    {...passThroughProps} />
}

export const AuAccordion = (props) => {
  const {
    className,
    ...passThroughProps
  } = props

  const _className = [
    className,
    'au-accordion',
    0
  ]
  .filter(Boolean).join(' ')

  const Cmp = props.cmp || 'div'

  return <Cmp
    className={_className}
    {...passThroughProps} />
}

export const AuAccordionPanel = (props) => {
  const {
    className,
    active,
    ...passThroughProps
  } = props

  const _className = [
    className,
    'au-accordion-panel',
    active && 'au-accordion-panel-active'
  ]
  .filter(Boolean).join(' ')

  const Cmp = props.cmp || 'div'

  return <Cmp
    className={_className}
    {...passThroughProps} />
}

export const AuAccordionHeader = (props) => {
  const {
    className,
    ...passThroughProps
  } = props

  const _className = [
    className,
    'au-accordion-header',
    0
  ]
  .filter(Boolean).join(' ')

  const Cmp = props.cmp || 'div'

  return <Cmp
    className={_className}
    {...passThroughProps} />
}

export const AuAccordionBody = (props) => {
  const {
    className,
    ...passThroughProps
  } = props

  const _className = [
    className,
    'au-accordion-body',
    0
  ]
  .filter(Boolean).join(' ')

  const Cmp = props.cmp || 'div'

  return <Cmp
    className={_className}
    {...passThroughProps} />
}

export const AuAlert = (props) => {
  const {
    className,
    flat,
    info,
    primary,
    success,
    warning,
    danger,
    ...passThroughProps
  } = props

  const _className = [
    className,
    'au-alert',
    flat && 'au-alert-flat',
    info && 'au-alert-info',
    primary && 'au-alert-primary',
    success && 'au-alert-success',
    warning && 'au-alert-warning',
    danger && 'au-alert-danger'
  ]
  .filter(Boolean).join(' ')

  const Cmp = props.cmp || 'p'

  return <Cmp
    className={_className}
    {...passThroughProps} />
}

export const AuButton = (props) => {
  const {
    className,
    secondary,
    tertiary,
    cta,
    actions,
    sm,
    area,
    link,
    text,
    badge,
    info,
    primary,
    success,
    warning,
    danger,
    ...passThroughProps
  } = props

  const _className = [
    className,
    'au-btn',
    secondary && 'au-btn-secondary',
    tertiary && 'au-btn-tertiary',
    cta && 'au-btn-cta',
    actions && 'au-btn-actions',
    sm && 'au-btn-sm',
    area && 'au-btn-area',
    link && 'au-btn-link',
    text && 'au-btn-text',
    badge && 'au-btn-badge',
    info && 'au-btn-info',
    primary && 'au-btn-primary',
    success && 'au-btn-success',
    warning && 'au-btn-warning',
    danger && 'au-btn-danger'
  ]
  .filter(Boolean).join(' ')

  const Cmp = props.cmp || 'button'

  return <Cmp
    className={_className}
    {...passThroughProps} />
}

export const AuCard = (props) => {
  const {
    className,
    muted,
    info,
    primary,
    success,
    warning,
    danger,
    ...passThroughProps
  } = props

  const _className = [
    className,
    'au-card',
    muted && 'au-card-muted',
    info && 'au-card-info',
    primary && 'au-card-primary',
    success && 'au-card-success',
    warning && 'au-card-warning',
    danger && 'au-card-danger'
  ]
  .filter(Boolean).join(' ')

  const Cmp = props.cmp || 'div'

  return <Cmp
    className={_className}
    {...passThroughProps} />
}

export const AuCardHeader = (props) => {
  const {
    className,
    ...passThroughProps
  } = props

  const _className = [
    className,
    'au-card-header',
    0
  ]
  .filter(Boolean).join(' ')

  const Cmp = props.cmp || 'div'

  return <Cmp
    className={_className}
    {...passThroughProps} />
}

export const AuClose = (props) => {
  const {
    className,
    ...passThroughProps
  } = props

  const _className = [
    className,
    'au-close',
    0
  ]
  .filter(Boolean).join(' ')

  const Cmp = props.cmp || 'span'

  return <Cmp
    className={_className}
    {...passThroughProps} />
}

export const AuDropdown = (props) => {
  const {
    className,
    open,
    ...passThroughProps
  } = props

  const _className = [
    className,
    'au-dropdown',
    open && 'au-dropdown-open'
  ]
  .filter(Boolean).join(' ')

  const Cmp = props.cmp || 'div'

  return <Cmp
    className={_className}
    {...passThroughProps} />
}

export const AuDropdownButton = (props) => {
  const {
    className,
    ...passThroughProps
  } = props

  const _className = [
    className,
    'au-dropdown-button',
    0
  ]
  .filter(Boolean).join(' ')

  const Cmp = props.cmp || 'div'

  return <Cmp
    className={_className}
    {...passThroughProps} />
}

export const AuDropdownBackdrop = (props) => {
  const {
    className,
    ...passThroughProps
  } = props

  const _className = [
    className,
    'au-dropdown-backdrop',
    0
  ]
  .filter(Boolean).join(' ')

  const Cmp = props.cmp || 'div'

  return <Cmp
    className={_className}
    {...passThroughProps} />
}

export const AuDropdownMenu = (props) => {
  const {
    className,
    ...passThroughProps
  } = props

  const _className = [
    className,
    'au-dropdown-menu',
    0
  ]
  .filter(Boolean).join(' ')

  const Cmp = props.cmp || 'div'

  return <Cmp
    className={_className}
    {...passThroughProps} />
}

export const AuInput = (props) => {
  const {
    className,
    ...passThroughProps
  } = props

  const _className = [
    className,
    'au-input',
    0
  ]
  .filter(Boolean).join(' ')

  const Cmp = props.cmp || 'input'

  return <Cmp
    className={_className}
    {...passThroughProps} />
}

export const AuCheckbox = (props) => {
  const {
    className,
    ...passThroughProps
  } = props

  const _className = [
    className,
    'au-checkbox',
    0
  ]
  .filter(Boolean).join(' ')

  const Cmp = props.cmp || 'input'

  return <Cmp
    className={_className}
    type='checkbox'
    {...passThroughProps} />
}

export const AuRadio = (props) => {
  const {
    className,
    ...passThroughProps
  } = props

  const _className = [
    className,
    'au-radio',
    0
  ]
  .filter(Boolean).join(' ')

  const Cmp = props.cmp || 'input'

  return <Cmp
    className={_className}
    type='radio'
    {...passThroughProps} />
}

export const AuList = (props) => {
  const {
    className,
    slim,
    relaxed,
    selectable,
    ...passThroughProps
  } = props

  const _className = [
    className,
    'au-list',
    slim && 'au-list-slim',
    relaxed && 'au-list-relaxed',
    selectable && 'au-list-selectable'
  ]
  .filter(Boolean).join(' ')

  const Cmp = props.cmp || 'ul'

  return <Cmp
    className={_className}
    {...passThroughProps} />
}

export const AuListItem = (props) => {
  const {
    className,
    active,
    ...passThroughProps
  } = props

  const _className = [
    className,
    'au-list-item',
    active && 'au-list-item-active'
  ]
  .filter(Boolean).join(' ')

  const Cmp = props.cmp || 'li'

  return <Cmp
    className={_className}
    {...passThroughProps} />
}

export const AuMarker = (props) => {
  const {
    className,
    placeholder,
    muted,
    info,
    primary,
    success,
    warning,
    danger,
    ...passThroughProps
  } = props

  const _className = [
    className,
    'au-marker',
    placeholder && 'au-marker-placeholder',
    muted && 'au-marker-muted',
    info && 'au-marker-info',
    primary && 'au-marker-primary',
    success && 'au-marker-success',
    warning && 'au-marker-warning',
    danger && 'au-marker-danger'
  ]
  .filter(Boolean).join(' ')

  const Cmp = props.cmp || 'span'

  return <Cmp
    className={_className}
    {...passThroughProps} />
}

export const AuPill = (props) => {
  const {
    className,
    active,
    info,
    primary,
    success,
    warning,
    danger,
    ...passThroughProps
  } = props

  const _className = [
    className,
    'au-pill',
    active && 'au-pill-active',
    info && 'au-pill-info',
    primary && 'au-pill-primary',
    success && 'au-pill-success',
    warning && 'au-pill-warning',
    danger && 'au-pill-danger'
  ]
  .filter(Boolean).join(' ')

  const Cmp = props.cmp || 'span'

  return <Cmp
    className={_className}
    {...passThroughProps} />
}

export const AuPillNav = (props) => {
  const {
    className,
    active,
    ...passThroughProps
  } = props

  const _className = [
    className,
    'au-pill-nav',
    'au-pill',
    active && 'au-pill-nav-active'
  ]
  .filter(Boolean).join(' ')

  const Cmp = props.cmp || 'a'

  return <Cmp
    className={_className}
    {...passThroughProps} />
}

export const AuLabel = (props) => {
  const {
    className,
    active,
    info,
    primary,
    success,
    warning,
    danger,
    ...passThroughProps
  } = props

  const _className = [
    className,
    'au-label',
    active && 'au-label-active',
    info && 'au-label-info',
    primary && 'au-label-primary',
    success && 'au-label-success',
    warning && 'au-label-warning',
    danger && 'au-label-danger'
  ]
  .filter(Boolean).join(' ')

  const Cmp = props.cmp || 'span'

  return <Cmp
    className={_className}
    {...passThroughProps} />
}

export const AuShadow = (props) => {
  const {
    className,
    short,
    medium,
    tall,
    ...passThroughProps
  } = props

  const _className = [
    className,
    'au-shadow',
    short && 'au-shadow-short',
    medium && 'au-shadow-medium',
    tall && 'au-shadow-tall'
  ]
  .filter(Boolean).join(' ')

  const Cmp = props.cmp || 'div'

  return <Cmp
    className={_className}
    {...passThroughProps} />
}

export const AuTable = (props) => {
  const {
    className,
    slim,
    relaxed,
    striped,
    borderless,
    info,
    primary,
    success,
    warning,
    danger,
    ...passThroughProps
  } = props

  const _className = [
    className,
    'au-table',
    slim && 'au-table-slim',
    relaxed && 'au-table-relaxed',
    striped && 'au-table-striped',
    borderless && 'au-table-borderless',
    info && 'au-table-info',
    primary && 'au-table-primary',
    success && 'au-table-success',
    warning && 'au-table-warning',
    danger && 'au-table-danger'
  ]
  .filter(Boolean).join(' ')

  const Cmp = props.cmp || 'table'

  return <Cmp
    className={_className}
    {...passThroughProps} />
}

export const AuTableRow = (props) => {
  const {
    className,
    ...passThroughProps
  } = props

  const _className = [
    className,
    'au-table-row',
    0
  ]
  .filter(Boolean).join(' ')

  const Cmp = props.cmp || 'tr'

  return <Cmp
    className={_className}
    {...passThroughProps} />
}

export const AuTableCol = (props) => {
  const {
    className,
    checkbox,
    text,
    data,
    ...passThroughProps
  } = props

  const _className = [
    className,
    'au-col',
    checkbox && 'au-col-checkbox',
    text && 'au-col-text',
    data && 'au-col-data'
  ]
  .filter(Boolean).join(' ')

  const Cmp = props.cmp || 'td'

  return <Cmp
    className={_className}
    {...passThroughProps} />
}

export const AuGrid = (props) => {
  const {
    className,
    info,
    primary,
    success,
    warning,
    danger,
    ...passThroughProps
  } = props

  const _className = [
    className,
    'au-grid',
    info && 'au-grid-info',
    primary && 'au-grid-primary',
    success && 'au-grid-success',
    warning && 'au-grid-warning',
    danger && 'au-grid-danger'
  ]
  .filter(Boolean).join(' ')

  const Cmp = props.cmp || 'div'

  return <Cmp
    className={_className}
    {...passThroughProps} />
}

export const AuCell = (props) => {
  const {
    className,
    divider,
    row,
    checkbox,
    text,
    data,
    info,
    primary,
    success,
    warning,
    danger,
    ...passThroughProps
  } = props

  const _className = [
    className,
    'au-cell',
    divider && 'au-cell-divider',
    row && 'au-cell-row',
    checkbox && 'au-cell-checkbox',
    text && 'au-cell-text',
    data && 'au-cell-data',
    info && 'au-cell-info',
    primary && 'au-cell-primary',
    success && 'au-cell-success',
    warning && 'au-cell-warning',
    danger && 'au-cell-danger'
  ]
  .filter(Boolean).join(' ')

  const Cmp = props.cmp || 'div'

  return <Cmp
    className={_className}
    {...passThroughProps} />
}

export const AuTextarea = (props) => {
  const {
    className,
    ...passThroughProps
  } = props

  const _className = [
    className,
    'au-input',
    0
  ]
  .filter(Boolean).join(' ')

  const Cmp = props.cmp || 'textarea'

  return <Cmp
    className={_className}
    {...passThroughProps} />
}

export const AuTabContainer = (props) => {
  const {
    className,
    ...passThroughProps
  } = props

  const _className = [
    className,
    'au-tab-container',
    0
  ]
  .filter(Boolean).join(' ')

  const Cmp = props.cmp || 'ul'

  return <Cmp
    className={_className}
    {...passThroughProps} />
}

export const AuTab = (props) => {
  const {
    className,
    ...passThroughProps
  } = props

  const _className = [
    className,
    'au-tab',
    0
  ]
  .filter(Boolean).join(' ')

  const Cmp = props.cmp || 'li'

  return <Cmp
    className={_className}
    {...passThroughProps} />
}

export const AuTabContent = (props) => {
  const {
    className,
    ...passThroughProps
  } = props

  const _className = [
    className,
    'au-tab-content',
    0
  ]
  .filter(Boolean).join(' ')

  const Cmp = props.cmp || 'div'

  return <Cmp
    className={_className}
    {...passThroughProps} />
}
